const ADD_ERROR = 'ADD_ERROR';
const REMOVE_ERROR = 'REMOVE_ERROR';

const SET_CURRENT_USER = 'SET_CURRENT_USER';

const SET_CURRENT_POLL = 'SET_CURRENT_POLL';
const SET_POLLS = 'SET_POLLS';

export { ADD_ERROR, REMOVE_ERROR, SET_CURRENT_POLL, SET_CURRENT_USER, SET_POLLS };